### ISSUE TITLE
Bug d'affichage crayon !

### ISSUE THREAD

**Issue by Fezlight** [elythiel/mge-monopoly-nuxt#5]
Steps to reproduce :
-> Mobile mode
-> Resfresh page
-> Desktop mode

The pencil is inside forms, so bad !!!!!!

![image](https://user-images.githubusercontent.com/8619331/203982085-5fcef4da-106a-4148-a730-8c6381ee7b8d.png)

**Comment by morganegervasoni** [comment]
Ah ouais on en est là. Ça ajoute des bugs ! ahaha :D

**Comment by elythiel** [comment]
Fixed on : https://github.com/elythiel/mge-monopoly-nuxt/pull/6
